apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-actions-lab-app
spec:
  selector:
    matchLabels:
      app: gh-actions-lab-app
  template:
    metadata:
      labels:
        app: gh-actions-lab-app
    spec:
      containers:
      - name: gh-actions-lab-app-container
        image: rukasu/github-actions-laboratory:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: gh-actions-lab-service
spec:
  type: NodePort
  selector:
    app: gh-actions-lab-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
    protocol: TCP
