name: actions-lab-workflow
on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:

  # docker login
  # build image
  # push image
  # docker logout
  # update image on k8s

  CI:
    name: "code integration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: rukasu/github-actions-laboratoy:latest

