name: actions-lab-workflow
on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:

  # docker login
  # build image
  # push image
  # docker logout

  CI:
    name: "code integration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            rukasu/github-actions-laboratory:v${{ github.run_number }}
            rukasu/github-actions-laboratory:latest

  # access the cluster
  # apply the deployment to update image on k8s

  CD:
    name: "project delivery"
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Connect via kubeconfig
        uses: azure/k8s-set-context@v4.0.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Apply deployment manifest
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yml
          images: 'rukasu/github-actions-laboratory:v${{ github.run_number }}'