name: actions-lab-workflow
on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  setup-inicial:
    name: "setup de ambiente"
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22.0
    steps:
      - name: "atualização e instalação"
        run: apk update && apk add curl
      - name: "dando um curl"
        run: curl "http://google.com"
